# Generated by Django 5.1.1 on 2026-02-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_profile_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeforces_rating', models.CharField(max_length=100)),
                ('codechef_star', models.CharField(max_length=50)),
                ('leetcode', models.CharField(blank=True, max_length=20, null=True)),
                ('total_problem_solved', models.IntegerField()),
            ],
        ),
    ]
