# Generated by Django 5.1.1 on 2026-02-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_technical_expertise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding_profile_detail',
            name='total_contest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
