# Generated by Django 5.1.1 on 2026-02-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_coding_profile_detail_total_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coding_profile_detail',
            name='codechef_rating',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coding_profile_detail',
            name='codeforces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='coding_profile_detail',
            name='codechef_star',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
